[[section-introduction-and-goals]]
== Introduction and Goals
The DeDe shopping simulator is the main application that our team will be developing for the subject of Software Architecture.

.Members of group en3b:
    * Celia Melendi Lavandera
    * Jesús Alonso García
    * Mario Lombas Calderón
    * Nicolás Lozano García
    * Óscar Pérez Arruñada


DeDe will be an application to simulate the management of an online shop, including the customer view, the delivery of items and the visualization of the orders. 

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

The application will be run online, either on Heroku or in a similar platform. Every user action will work using pods.
Users will be able to browse the catalog and order things from their pods. Then, the app will calculate the price based on the location of the user.

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
The quality goals are the following:

==== Learnability/Usability:
The system must make it easy for novice users or non-technical peaple to learn quickly. Also allows steady progression to expertise.

==== Decentralization: 
The application will not store personal information from customers but will obtain that information from the user’s pods given that the users give the necessary permissions to the shopping system.

==== Security/Privacy:
The system will ask for permissionss in order to ensure security.It will not lead to any security problems by not storing personal information about the user.

==== Accessibilty:
High accessibility should be reached thanks to a continuous integration system.

==== Testability: 
The system should be ready for testing purposes: quality of test strategy and tests code coverage.


=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Teachers | The teachers assigned to the group | Provide project guidance, doubt resolution, supervision...
| Developers | The students that are part of the development team | Everything related with design and development issues
| Final users | The clients that will interact with the system | The aim of the application, the users that should be satisfied by the system's benefits
| Classmates | Classmates from the other projects | Since it is not about a competition, the development team can obtain help from other development teams by solving doubts or teaching some techniques, for example.
| SOLID community | The SOLID community | Users related with SOLID community that are interested on making the product better
| Inrupt and empathy | Those enterprises | Interested on knowing the skills of the students related with the project and the project itself
|===
