[[section-solution-strategy]]
== Solution Strategy

=== Technology decisions

A summary of the technical decisions that we have taken so far:

    * **MongoDB**: The DMBS of our choice.
    * **Express**: A framework to handle the backend of our application.
    * **Redux**: Used to keep the contents of user's carts.
    * **Heroku**: The cloud platform where we deployed our app.


=== Decisions about the the top-level decomposition of the system

The system is mainly composed of two parts: The webapp and the REST API.

The webapp is designed using React. It interfaces with the REST API to fetch
data and to retrieve Pod information.

The REST API is made with Express in Node.js. It is formed by two essential systems: the API as such and the Solid API.
The API interfaces with MongoDB to store and retrieve data, while the Solid API, which is another RESTful API, interfaces with a facade of our own.

=== Decisions on how to achive key quality goals

This are the quality goals we focused on

    * **Usability**: We will try to develop an app that is easy to use.
    * **Responsiveness**: We will try to develop an app that has optimal or at least acceptable response times.
    * **Accessibilty**: We will try to develop an app that anyone can use.
    * **Security**: Thanks to Solid we will try to store as little sensitive information about the user in our servers as possible, taking the maximum possible information about the user from their own Pods.


=== Organizational decisions

* **Meetings and communication**: Our meetings will occur in person and online. For the online meetings we will use apps such as Microsoft Teams and Discord. To communicate the smaller things we will use a Whatsapp group chat.
* **Task organization**: To organize the tasks that we have to do for the app we will use the GitHub projects, a tool that displays our issues in a KanBan view. The main factor for this was its similarity to a tool we used in the IPS course and because it allows us to see our progress and our partners progress.
* **Development**: We will create branches for every task that involves touching the repository files. To merge the project of the branches with the master branch we will use pull request since we believe it's great for proof-reading and it forces us to "know" a bit about every part of the project so that we don't have future problems when we will work with each other's code.